### ISSUE TITLE
Quest Files are missing from HQM folder

### ISSUE THREAD

**Issue by rinOfTheStars** [aaronhowser1/Infinity-Evolved-Skyblock-HQM#1]
For some reason, when I attempt to download the quest pack, the Quest .json files are missing. I would think a reupload would fix this.

**Comment by aaronhowser1** [comment]
The json files in config\hqm\QuestFiles aren't necessary to use the quests, just the quests.hqm file in config\hqm. I will upload a v2 with the json files though.
